name              "nascent_workstation"
maintainer        "Steve Marshall"
maintainer_email  "steve@nascentguruism.com"
license           "MIT"
description       "Configure frequently-used tools for my Macs"
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           "0.0.1"
supports          "mac_os_x"

depends           "mac_os_x"
depends           "chruby"
depends           "dmg"
depends           "homebrew"
depends           "perl"
depends           "tar"
depends           "vagrant"
depends           "zip_app"
